########################################################################
# Config options for Duplicity host backup.
########################################################################

# GnuPG key ID used for encryption and signing.
gpg_key_id: xxxxxxxxx

# S3 bucket name and optional prefix in Duplicity URL format.
s3_url: s3+http://my-host-backup

# Create full backup if the last one is older than the specified period. Use Duplicity time format.
full_if_older_than: 1M

# Purge old backups, retaining only the last 3 full ones.
remove_all_but_n_full: 3

# Access Key of created S3
aws_access_key_id: xxxxxxxxxxxxxxxx

# Secret Key of created S3        
aws_secret_access_key: xxxxxxxxxxxxxxxx

# Directories to be backed up. Each one consists of a source (absolute path) and optional lists of
# include and exclude patterns in Duplicity format.
backup_dirs:
  - source: /home/<username>
    excludes:
      - /**/[Cc]ache
      - /**/.cache
      - /**/Trash
      - /**/Steam
      - /**/node_modules
      - /home/<username>/VirtualBox VMs
      - /home/<username>/.config/VirtualBox
      - /home/<username>/.mozilla
      - /home/<username>/.config/chromium
      - /home/<username>/.config/google-chrome
      - /home/<username>/.local/share/flatpak
      - /home/<username>/.wine
      - /home/<username>/.virtualenvs
      - /home/<username>/.local/share/virtualenvs
      - /home/<username>/.nvm
      - /home/<username>/Downloads
  - source: /etc